// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeFRZJMV_XEdJtJ_CJ4vKqg-NRuRDTRdY',
    appId: '1:394996571744:web:37158ece9d14edf738ed05',
    messagingSenderId: '394996571744',
    projectId: 'finance-project-3c5ed',
    authDomain: 'finance-project-3c5ed.firebaseapp.com',
    databaseURL: 'https://finance-project-3c5ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finance-project-3c5ed.firebasestorage.app',
    measurementId: 'G-WY0570051L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwn72ju35I5upRoOV1dx-ny3hq_8aaJH0',
    appId: '1:394996571744:android:a31e2dc21362de6138ed05',
    messagingSenderId: '394996571744',
    projectId: 'finance-project-3c5ed',
    databaseURL: 'https://finance-project-3c5ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finance-project-3c5ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvEH31uhEG_mqJNyFIoltGnqm71ySaAQ',
    appId: '1:394996571744:ios:bcd4c1032281975d38ed05',
    messagingSenderId: '394996571744',
    projectId: 'finance-project-3c5ed',
    databaseURL: 'https://finance-project-3c5ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finance-project-3c5ed.firebasestorage.app',
    androidClientId: '394996571744-qh54vmc08mf2ee0k88jvp097fcb2cvnh.apps.googleusercontent.com',
    iosClientId: '394996571744-qnbqusn1f290b9j3lpq9s6lcoq0rrorj.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvEH31uhEG_mqJNyFIoltGnqm71ySaAQ',
    appId: '1:394996571744:ios:bcd4c1032281975d38ed05',
    messagingSenderId: '394996571744',
    projectId: 'finance-project-3c5ed',
    databaseURL: 'https://finance-project-3c5ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finance-project-3c5ed.firebasestorage.app',
    androidClientId: '394996571744-qh54vmc08mf2ee0k88jvp097fcb2cvnh.apps.googleusercontent.com',
    iosClientId: '394996571744-qnbqusn1f290b9j3lpq9s6lcoq0rrorj.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeFRZJMV_XEdJtJ_CJ4vKqg-NRuRDTRdY',
    appId: '1:394996571744:web:23d759c766f7046138ed05',
    messagingSenderId: '394996571744',
    projectId: 'finance-project-3c5ed',
    authDomain: 'finance-project-3c5ed.firebaseapp.com',
    databaseURL: 'https://finance-project-3c5ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finance-project-3c5ed.firebasestorage.app',
    measurementId: 'G-3VC65VSR7T',
  );
}
